### ISSUE TITLE
Clicking the search button multiple times too fast causes undesired behavior

### ISSUE THREAD

**Issue by TheYarin** [HanaDigital/grev#13]
Clicking the search button multiple times too fast aggregates the results instead of clearing the previous ones before presenting the new ones.

**Comment by TheYarin** [comment]
Nice project, by the way!

**Comment by dr-nyt** [comment]
I tried clicking the search button on a repo link multiple times quickly, but I didn't see the issue you described. Could you go into detail on your steps to recreate this issue?

And thank you, I'm glad you like this project :D

**Comment by TheYarin** [comment]
I tried it again and it's still happening. Here's a photo of it:
![image](https://user-images.githubusercontent.com/15931306/125161105-1ee49c80-e189-11eb-93d0-6ba1a455f79a.png)

It feels like this happens when the response takes a little too long. Sometimes after 8 (fast) clicks, sometimes after 2.

**Comment by dr-nyt** [comment]
Is it possible for you to share which repository this happens for? Could you try doing the same with https://github.com/HanaDigital/NovelScraper

**Comment by TheYarin** [comment]
Same for NovelScraper:
![image](https://user-images.githubusercontent.com/15931306/125345902-c61c2c00-e361-11eb-8ea2-d63982501333.png)

I don't have a screen recording software unfortunately. I tried it on Firefox and almost couldn't replicate it, but then I tried clicking faster and for longer and at managed to replicate it. It was much harder than on chrome for some reason. It was harder to replicate on Chrome incognito, as well.

**Comment by TheYarin** [comment]
I looked at the code and it's probably a race condition in /src/app/app.component.ts.
When you click "search" the flow is something like:

```typescript
wipe()
...
await fetch(...)
...
this.releases.push(...)
```

so there's an opening for "wipe await wipe await push push" to take place.

**Comment by dr-nyt** [comment]
Just skimmed through the code, and it's a hot mess... How did I even write that code lol, no idea why it's working. I think I have a hacky way to fix this but the whole thing probably needs a rework and a port to react instead of angular. I'll get to it when I get the time since it's not a major issue.

**Comment by dr-nyt** [comment]
Just updated the website to a new framework, and now it's impossible to click multiple times.
