### ISSUE TITLE
Seeing 0 downloads for my repository releases

### ISSUE THREAD

**Issue by eyalroz** [HanaDigital/grev#22]
I was trying to use  https://hanadigital.github.io/grev/ for two repositories of mine:

https://hanadigital.github.io/grev/?user=eyalroz&repo=cuda-api-wrappers
https://hanadigital.github.io/grev/?user=eyalroz&repo=printf

and it told me there were no downloads at all. Except that there have been, for sure.

**Comment by dr-nyt** [comment]
I use the api provided by github to calculate how many downloads you have. The api shows no assets in your release, and hence no download count. Do you just create releases for the current version of the repository in a zipped file generated by default? Github might not be tracking those for some reason, I'll have to check.

**Comment by eyalroz** [comment]
> Do you just create releases for the current version of the repository in a zipped file generated by default? 

Yes, I release the source, not any binaries / compiled artifacts.

**Comment by dr-nyt** [comment]
Unfortunately the github api doesn't track those. I'd try looking at alternatives if there are any. If it is important to you then maybe consider uploading zipped source manually so they get tracked.

**Comment by eyalroz** [comment]
Hmm. An interesting suggestion.

**Comment by dr-nyt** [comment]
Since this is an issue related to the GitHub API, I'll be closing this issue.

**Comment by eyalroz** [comment]
But don't you think it's a problem that your tool says it lets you "View the total download count of all releases" though it doesn't, and "View the download count of every individual release" though it doesn't?

**Comment by dr-nyt** [comment]
It does say, and the GitHub API says that too. But if Microsoft can't pull it off then there is little I can do. Although this does seem to be a bug, I'll ask someone on the GitHub dev team to look into it, but we are all at their mercy.
