### ISSUE TITLE
Feature request: show download counts on user overview page

### ISSUE THREAD

**Issue by Tazzios** [HanaDigital/grev#31]
Show the download count of the latest release on the overview page from the user.

**Comment by dr-nyt** [comment]
I'd love to do this but it will possibly create issues for users with a lot of released repositories because the Github API has a limited number of requests a user can make in a certain amount of time. Requesting the API for multiple repositories with many a lot will quickly exceed that limit.

**Comment by Tazzios** [comment]
Understandable, maybe overcome this limit by spliting repository to 20(random amount) per page ? 
So show the first 20 repositories with counter and if you go to the next repository pages the next 20 counters will be loaded.
