### ISSUE TITLE
Feature: Any chance it can track unique downloaders?

### ISSUE THREAD

**Issue by tpmccallum** [HanaDigital/grev#36]
It would be great to track unique downloaders in the same way that GitHub insights can show unique cloners. It might have to be ip based etc. instead of account holder based. If possible it could show vague location i.e. by country etc.
Just food for thought.

**Comment by dr-nyt** [comment]
This repo uses the github api to fetch the user data. Unfortunately this api doesn't provide the relevant data to implement this feature.
