### ISSUE TITLE
When release titles are too long there are partially hidden and the container need horizontal scrolling

### ISSUE THREAD

**Issue by 255kb** [HanaDigital/grev#4]
In the list of releases, when a title is too long, the container requires some horizontal scrolling, and the beginning of the title is partially hidden.
You could consider moving the second box under the "latest release", maybe larger. 
Also, in the list of releases it could be helpful to display the tag also.

![image](https://user-images.githubusercontent.com/7489814/94263464-5d300880-ff35-11ea-98e3-45c1f61720dc.png)

By the way, thanks for this nifty tool :)

**Comment by dr-nyt** [comment]
I had a gut feeling that might end up as a problem. I really like the current design as it shows you everything right there. Do you think if just limiting the number of characters in the line is a good idea?

**Comment by 255kb** [comment]
yes sure, I would say most important is the tag and the download count. The title of the release is secondary I think.

**Comment by dr-nyt** [comment]
This issue is fixed. You will need to remove the cache to see the changes. 

Thanks for bringing this up!
