### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by MichaelDavidGK** [HanaDigital/grev#43]
Seems to be broken, always shows 0

**Comment by dr-nyt** [comment]
Could I know what URL you use?

**Comment by dr-nyt** [comment]
Unfortunately the github API doesn't keep track of the zipped source code you release. It will only count the downloads for other assets in your release. For example [here](https://github.com/HanaDigital/NovelScraper/releases/tag/v2.0.6), it only tracks `latest.yml`, `novelscraper-Setup-2.0.6.exe` & `novelscraper-Setup-2.0.6.exe.blockmap`

I'll close this for now, but if you have any other comments, feel free to open it back up
