### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by asheroto** [HanaDigital/grev#47]
Hey @HanaDigital, I ran across a security concern I wanted to mention. If you set up a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) so I can submit a private issue.

**Comment by dr-nyt** [comment]
A little late, but I created a security policy

**Comment by asheroto** [comment]
Thank you. Unfortunately I've forgotten what the security issue was. I can't seem to find any notes I made on it, so I'll close the issue for now. 😊
