### ISSUE TITLE
Incorrect download numbers for GitHub repository 

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [HanaDigital/grev#49]
Hello, thank you for creating GREV. Our team uses it frequently for internal reporting. I wanted to report some inconsistency with the download counts displayed on https://hanadigital.github.io/grev/?user=cisagov&repo=scubagear. Last week the download count for our latest release, v1.3.0, was around 422. This week it seemed to have reset to 0. Since then it has increased to 4 and now 38 as more users have downloaded from our repository. 

I did some personal investigating to see if the GitHub API was experiencing an outage but haven't found anything relevant. Maybe you have seen similar issues or know more info?

**Comment by dr-nyt** [comment]
Hi, I see that the original release was published on `2024-06-07T00:53:22Z`, but the asset in the release was created on `2024-08-02T15:17:04Z`. That is almost a 2 month difference. Is it possible that you deleted an asset and re-uploaded a new one?

If so then I would suggest always doing a new release when you need to update an asset to keep things consistent with the api.

**Comment by mitchelbaker-cisa** [comment]
> Hi, I see that the original release was published on `2024-06-07T00:53:22Z`, but the asset in the release was created on `2024-08-02T15:17:04Z`. That is almost a 2 month difference. Is it possible that you deleted an asset and re-uploaded a new one?
> 
> If so then I would suggest always doing a new release when you need to update an asset to keep things consistent with the api.
> 
> Edit: This is [the api endpoint](https://api.github.com/repos/cisagov/scubagear/releases?page=1&per_page=100) that the web app looks at.

We prepared a v1.4.0 draft last Friday and yes I'm seeing that the asset for v1.3.0 was updated on the same date, 08/02. Thanks for your insight and linking the api endpoint, it helps!

**Comment by dr-nyt** [comment]
Glad you have tracked down the issue. So I'm assuming `v1.3.0` was replaced with `v1.4.0` on the same release. The api doesn't keep track of the deleted assets, so there is nothing further that can be done as far as I'm aware.

I will close this issue for now.
